# Generated by Django 5.0.4 on 2024-04-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_hora_inicio_pedido_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
