# Generated by Django 5.0.4 on 2024-05-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_producto_descripcion_alter_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('GF', 'Gluten Free'), ('VG', 'Vegan'), ('WW', 'With Wheat'), ('SF', 'Sugar Free')], default='WW', max_length=2),
        ),
    ]
