# Generated by Django 5.0.4 on 2024-05-03 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_packaging_alter_producto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='Etiqueta',
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='packaging',
            name='etiqueta',
            field=models.CharField(choices=[('Gluten Free', 'Gluten Free'), ('Vegan', 'Vegan'), ('With Wheat', 'With Wheat'), ('Sugar Free', 'Sugar Free'), ('No Label', 'No Label')], default='No Label', max_length=20),
        ),
    ]
